version: "3.3"
services:
  app:
    build: ./app
    expose:
      - 5000
  nginx:
    build: ./nginx
    depends_on:
      - app  
    ports:
    - 443:443
  vouch:
    build: ./vouch
    depends_on:
      - nginx
    ports:
    - 9090
